config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
]

user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('', home, name='home'),
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('dashboard/', dashboard, name='dashboard'),
]

user/models.py
from django.conf import settings
from django.db import models


User = settings.AUTH_USER_MODEL


class User(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=False, verbose_name='active')

    def __str__(self):
        return f'User: {self.user.username}'

user/forms.py
from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput, help_text='')
    password2 = forms.CharField(label='Confirmation Password', widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ['username', 'password1', 'password2',]
        
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].help_text = ''

    def clear_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            raise forms.ValidationError("Password Mismatch!")
        return self.cleaned_data['password2']


class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

user/views.py
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.shortcuts import render, redirect
from .forms import LoginForm, RegisterForm
from .models import User


def home(request):
    return render(request, 'user/home.html')


@login_required
def dashboard(request):
    return render(request, 'user/dashboard.html')


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            User.objects.create(user=user)

            return render(request, 'user/register_done.html', {'user': user})
    else:
        form = RegisterForm()
    
    return render(request, 'user/register.html', {'form': form})


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            user = authenticate(request,
                                username=form.cleaned_data['username'],
                                password=form.cleaned_data['password']
                                )
                                
            if user is not None:
                if user.is_active:
                    auth_login(request, user)

                    return redirect('user:dashboard')
                else:
                    return redirect('user:home')
        else:
            return render(request, 'user/login.html', {'form': form})
    else:
        form = LoginForm()

    return render(request, 'user/login.html', {'form': form})


@login_required
def logout(request):
    auth_logout(request)
    return redirect('user:home')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Authentication{% block title %}{% endblock %}</title>
</head>

<body style="text-align: center;">
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/user/dashboard.html
{% extends 'base.html' %}

{% block title %} | Dashboard{% endblock %}

{% block content %}
    <h1>Dashboard</h1>
    <h3>
        You have logged in as {{user.username | capfirst}}
        <p>
            <a href="{% url 'user:logout' %}">Logout</a>
        </p>
    </h3>
{% endblock %}

templates/user/home.html
{% extends 'base.html' %}

{% block title %} | Home{% endblock %}

{% block content %}
    <h1>Home</h1>
    <h3>
        <a href="{% url 'user:register' %}">Register</a>
    </h3>
    <h3>
        <a href="{% url 'user:login' %}">Login</a>
    </h3>
{% endblock %}

templates/user/login.html
{% extends 'base.html' %}

{% block title %} | Login{% endblock %}

{% block content %}
    <h1>Login</h1>
    <h3>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <p>
                <input type="submit" value="Login">
            </p>
            <p>
                Don't have an account? <a href="{% url 'user:register' %}">Create an account</a>.
            </p>
        </form>
    </h3>
{% endblock %}

templates/user/register.html
{% extends 'base.html' %}

{% block title %} | Registration Form{% endblock %}

{% block content %}
    <h1>Create Account</h1>
    <p>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <p>
                <input type="submit" value="Create Account">
            </p>
        </form>
    </p>
{% endblock %}

templates/user/register_done.html
{% extends 'base.html' %}

{% block title %} | Registration Done{% endblock %}

{% block content %}
    <h1>Registration successful!</h1>
    <p>
        Now you can <a href="{% url 'user:login' %}">login</a> to your account.
    </p>
{% endblock %}